# Generated by Django 4.2.4 on 2023-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snsmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='snsmodel',
            name='readtext',
        ),
        migrations.RemoveField(
            model_name='snsmodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='snsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
