# Generated by Django 4.2.4 on 2023-09-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedImage',
            new_name='re_UploadedImage',
        ),
    ]
