# Generated by Django 4.2.4 on 2023-09-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0002_remove_image_title_image_masking_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='masking',
            new_name='mask',
        ),
    ]
