# Generated by Django 4.2.4 on 2023-09-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0003_snsmodel_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
