# Generated by Django 4.2.4 on 2023-09-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0004_new_uploadedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_UploadedImage',
        ),
        migrations.DeleteModel(
            name='re_UploadedImage',
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
