# Generated by Django 4.2.4 on 2023-09-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0005_alter_snsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
