# Generated by Django 4.2.4 on 2023-09-13 06:51

from django.db import migrations, models
import stable_ai.models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0006_snsmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=stable_ai.models.changePath),
        ),
    ]
