# Generated by Django 4.2.4 on 2023-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_ai', '0007_snsmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsmodel',
            name='content',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
